// <auto-generated />
using System;
using CookingRecipe.Web.Infrastructures.Domain.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CookingRecipe.Web.Migrations
{
    [DbContext(typeof(DefaultDbContext))]
    [Migration("20210525045645_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("CookingRecipe.Web.Infrastructures.Domain.Models.Cooking", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("IngredientId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("InstructionId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Cookings");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8b578d2c-8819-4c50-bf9a-ab33cd6a1ea4"),
                            CreatedAt = new DateTime(2021, 5, 25, 4, 56, 44, 774, DateTimeKind.Utc).AddTicks(7194),
                            Name = "Adobong Baboy",
                            UpdatedAt = new DateTime(2021, 5, 25, 4, 56, 44, 774, DateTimeKind.Utc).AddTicks(7197)
                        },
                        new
                        {
                            Id = new Guid("765d31e6-e9cb-4f11-a9be-4b38518db304"),
                            CreatedAt = new DateTime(2021, 5, 25, 4, 56, 44, 774, DateTimeKind.Utc).AddTicks(7257),
                            Name = "Tinolang Manok",
                            UpdatedAt = new DateTime(2021, 5, 25, 4, 56, 44, 774, DateTimeKind.Utc).AddTicks(7258)
                        },
                        new
                        {
                            Id = new Guid("04a8beb5-d3fc-4cab-9f2e-78ee68fb2555"),
                            CreatedAt = new DateTime(2021, 5, 25, 4, 56, 44, 774, DateTimeKind.Utc).AddTicks(7265),
                            Name = "Sinigang Isda",
                            UpdatedAt = new DateTime(2021, 5, 25, 4, 56, 44, 774, DateTimeKind.Utc).AddTicks(7267)
                        },
                        new
                        {
                            Id = new Guid("daf66e9e-f51c-41f6-bde7-196022b00bdb"),
                            CreatedAt = new DateTime(2021, 5, 25, 4, 56, 44, 774, DateTimeKind.Utc).AddTicks(7273),
                            Name = "Sinigang Baboy",
                            UpdatedAt = new DateTime(2021, 5, 25, 4, 56, 44, 774, DateTimeKind.Utc).AddTicks(7274)
                        },
                        new
                        {
                            Id = new Guid("5d15a152-4a5f-4c49-925c-92ff2cabac4e"),
                            CreatedAt = new DateTime(2021, 5, 25, 4, 56, 44, 774, DateTimeKind.Utc).AddTicks(7280),
                            Name = "Afritada",
                            UpdatedAt = new DateTime(2021, 5, 25, 4, 56, 44, 774, DateTimeKind.Utc).AddTicks(7280)
                        },
                        new
                        {
                            Id = new Guid("49d33a16-2cc2-41af-8a35-568f08bcd904"),
                            CreatedAt = new DateTime(2021, 5, 25, 4, 56, 44, 774, DateTimeKind.Utc).AddTicks(7293),
                            Name = "Dinuguan",
                            UpdatedAt = new DateTime(2021, 5, 25, 4, 56, 44, 774, DateTimeKind.Utc).AddTicks(7294)
                        },
                        new
                        {
                            Id = new Guid("b2fdf377-576b-4f61-822f-c847cc0b7515"),
                            CreatedAt = new DateTime(2021, 5, 25, 4, 56, 44, 774, DateTimeKind.Utc).AddTicks(7300),
                            Name = "Sisig",
                            UpdatedAt = new DateTime(2021, 5, 25, 4, 56, 44, 774, DateTimeKind.Utc).AddTicks(7301)
                        },
                        new
                        {
                            Id = new Guid("f17f738d-376c-403e-a503-fc8837dbddfc"),
                            CreatedAt = new DateTime(2021, 5, 25, 4, 56, 44, 774, DateTimeKind.Utc).AddTicks(7306),
                            Name = "Daing",
                            UpdatedAt = new DateTime(2021, 5, 25, 4, 56, 44, 774, DateTimeKind.Utc).AddTicks(7307)
                        },
                        new
                        {
                            Id = new Guid("16aa5e0c-886e-4807-b1de-13942600ce23"),
                            CreatedAt = new DateTime(2021, 5, 25, 4, 56, 44, 774, DateTimeKind.Utc).AddTicks(7312),
                            Name = "Bicol Express",
                            UpdatedAt = new DateTime(2021, 5, 25, 4, 56, 44, 774, DateTimeKind.Utc).AddTicks(7313)
                        },
                        new
                        {
                            Id = new Guid("1ff74660-f576-4fbf-8691-fe8e28358a64"),
                            CreatedAt = new DateTime(2021, 5, 25, 4, 56, 44, 774, DateTimeKind.Utc).AddTicks(7370),
                            Name = "Chop Suey",
                            UpdatedAt = new DateTime(2021, 5, 25, 4, 56, 44, 774, DateTimeKind.Utc).AddTicks(7371)
                        },
                        new
                        {
                            Id = new Guid("b6e97a13-c953-46b3-afe2-4d709e722e3b"),
                            CreatedAt = new DateTime(2021, 5, 25, 4, 56, 44, 774, DateTimeKind.Utc).AddTicks(7378),
                            Name = "Pork Bistek",
                            UpdatedAt = new DateTime(2021, 5, 25, 4, 56, 44, 774, DateTimeKind.Utc).AddTicks(7379)
                        },
                        new
                        {
                            Id = new Guid("6cc73fbb-39a4-4df2-9390-9e678409d30e"),
                            CreatedAt = new DateTime(2021, 5, 25, 4, 56, 44, 774, DateTimeKind.Utc).AddTicks(7384),
                            Name = "Ginataang Langka",
                            UpdatedAt = new DateTime(2021, 5, 25, 4, 56, 44, 774, DateTimeKind.Utc).AddTicks(7385)
                        },
                        new
                        {
                            Id = new Guid("6b7a50e7-a90e-4be6-a869-c33084c02bfe"),
                            CreatedAt = new DateTime(2021, 5, 25, 4, 56, 44, 774, DateTimeKind.Utc).AddTicks(7391),
                            Name = "Beef Bulalo",
                            UpdatedAt = new DateTime(2021, 5, 25, 4, 56, 44, 774, DateTimeKind.Utc).AddTicks(7392)
                        },
                        new
                        {
                            Id = new Guid("96405bf3-5174-4596-9fb1-b45225cee1c9"),
                            CreatedAt = new DateTime(2021, 5, 25, 4, 56, 44, 774, DateTimeKind.Utc).AddTicks(7397),
                            Name = "Achara",
                            UpdatedAt = new DateTime(2021, 5, 25, 4, 56, 44, 774, DateTimeKind.Utc).AddTicks(7398)
                        },
                        new
                        {
                            Id = new Guid("0339bd26-b895-4471-8052-ab2ffe29be98"),
                            CreatedAt = new DateTime(2021, 5, 25, 4, 56, 44, 774, DateTimeKind.Utc).AddTicks(7405),
                            Name = "Paksiw Isda",
                            UpdatedAt = new DateTime(2021, 5, 25, 4, 56, 44, 774, DateTimeKind.Utc).AddTicks(7406)
                        });
                });

            modelBuilder.Entity("CookingRecipe.Web.Infrastructures.Domain.Models.Ingredient", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("CookingId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitCost")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("CookingId");

                    b.ToTable("Ingredients");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ca25c528-627b-4b80-9b91-02d06afc3c55"),
                            CookingId = new Guid("8b578d2c-8819-4c50-bf9a-ab33cd6a1ea4"),
                            CreatedAt = new DateTime(2021, 5, 25, 4, 56, 44, 775, DateTimeKind.Utc).AddTicks(410),
                            Name = "Chicken Thighs",
                            Quantity = 1,
                            UnitCost = 50m,
                            UpdatedAt = new DateTime(2021, 5, 25, 4, 56, 44, 775, DateTimeKind.Utc).AddTicks(413)
                        },
                        new
                        {
                            Id = new Guid("0b483fb6-f736-4baa-ab3c-d8f2a1e163c7"),
                            CookingId = new Guid("8b578d2c-8819-4c50-bf9a-ab33cd6a1ea4"),
                            CreatedAt = new DateTime(2021, 5, 25, 4, 56, 44, 775, DateTimeKind.Utc).AddTicks(509),
                            Name = "Vegetable Oil",
                            Quantity = 1,
                            UnitCost = 35m,
                            UpdatedAt = new DateTime(2021, 5, 25, 4, 56, 44, 775, DateTimeKind.Utc).AddTicks(511)
                        },
                        new
                        {
                            Id = new Guid("711b6d5a-19a3-44c8-81d9-8cb361fc01d3"),
                            CookingId = new Guid("8b578d2c-8819-4c50-bf9a-ab33cd6a1ea4"),
                            CreatedAt = new DateTime(2021, 5, 25, 4, 56, 44, 775, DateTimeKind.Utc).AddTicks(521),
                            Name = "Onion",
                            Quantity = 2,
                            UnitCost = 10m,
                            UpdatedAt = new DateTime(2021, 5, 25, 4, 56, 44, 775, DateTimeKind.Utc).AddTicks(522)
                        },
                        new
                        {
                            Id = new Guid("eeb8ba33-56c5-401a-967e-d3a9721dcd2a"),
                            CookingId = new Guid("8b578d2c-8819-4c50-bf9a-ab33cd6a1ea4"),
                            CreatedAt = new DateTime(2021, 5, 25, 4, 56, 44, 775, DateTimeKind.Utc).AddTicks(530),
                            Name = "Garlic",
                            Quantity = 5,
                            UnitCost = 10m,
                            UpdatedAt = new DateTime(2021, 5, 25, 4, 56, 44, 775, DateTimeKind.Utc).AddTicks(531)
                        },
                        new
                        {
                            Id = new Guid("e489d772-baa5-4e5b-ae96-60e49b0ce3f2"),
                            CookingId = new Guid("8b578d2c-8819-4c50-bf9a-ab33cd6a1ea4"),
                            CreatedAt = new DateTime(2021, 5, 25, 4, 56, 44, 775, DateTimeKind.Utc).AddTicks(541),
                            Name = "Vinegar",
                            Quantity = 1,
                            UnitCost = 7m,
                            UpdatedAt = new DateTime(2021, 5, 25, 4, 56, 44, 775, DateTimeKind.Utc).AddTicks(542)
                        },
                        new
                        {
                            Id = new Guid("48ba0fda-bceb-44eb-92c0-80b7460e7339"),
                            CookingId = new Guid("8b578d2c-8819-4c50-bf9a-ab33cd6a1ea4"),
                            CreatedAt = new DateTime(2021, 5, 25, 4, 56, 44, 775, DateTimeKind.Utc).AddTicks(554),
                            Name = "Soy sauce",
                            Quantity = 1,
                            UnitCost = 7m,
                            UpdatedAt = new DateTime(2021, 5, 25, 4, 56, 44, 775, DateTimeKind.Utc).AddTicks(555)
                        },
                        new
                        {
                            Id = new Guid("e1145858-0470-413d-99bc-a2507365f52f"),
                            CookingId = new Guid("8b578d2c-8819-4c50-bf9a-ab33cd6a1ea4"),
                            CreatedAt = new DateTime(2021, 5, 25, 4, 56, 44, 775, DateTimeKind.Utc).AddTicks(564),
                            Name = "Peppercorns",
                            Quantity = 1,
                            UnitCost = 5m,
                            UpdatedAt = new DateTime(2021, 5, 25, 4, 56, 44, 775, DateTimeKind.Utc).AddTicks(565)
                        },
                        new
                        {
                            Id = new Guid("8c63a87f-f380-48fb-860f-c77e82ee338c"),
                            CookingId = new Guid("8b578d2c-8819-4c50-bf9a-ab33cd6a1ea4"),
                            CreatedAt = new DateTime(2021, 5, 25, 4, 56, 44, 775, DateTimeKind.Utc).AddTicks(573),
                            Name = "Bay leaves",
                            Quantity = 4,
                            UnitCost = 3m,
                            UpdatedAt = new DateTime(2021, 5, 25, 4, 56, 44, 775, DateTimeKind.Utc).AddTicks(574)
                        },
                        new
                        {
                            Id = new Guid("646c08f6-fd0e-4eb2-8b97-21039f8f87eb"),
                            CookingId = new Guid("8b578d2c-8819-4c50-bf9a-ab33cd6a1ea4"),
                            CreatedAt = new DateTime(2021, 5, 25, 4, 56, 44, 775, DateTimeKind.Utc).AddTicks(582),
                            Name = "Green onion",
                            Quantity = 1,
                            UnitCost = 10m,
                            UpdatedAt = new DateTime(2021, 5, 25, 4, 56, 44, 775, DateTimeKind.Utc).AddTicks(583)
                        });
                });

            modelBuilder.Entity("CookingRecipe.Web.Infrastructures.Domain.Models.Instruction", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("CookingId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Step")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Time")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("TotalStep")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("CookingId");

                    b.ToTable("Instructions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b2152e67-b875-4a9d-a5ee-662b73ea6caf"),
                            CookingId = new Guid("8b578d2c-8819-4c50-bf9a-ab33cd6a1ea4"),
                            CreatedAt = new DateTime(2021, 5, 25, 4, 56, 44, 775, DateTimeKind.Utc).AddTicks(3118),
                            Step = "1st step : Chop and clean the ingredients and wash it",
                            Time = "",
                            TotalStep = 0,
                            UpdatedAt = new DateTime(2021, 5, 25, 4, 56, 44, 775, DateTimeKind.Utc).AddTicks(3121)
                        },
                        new
                        {
                            Id = new Guid("7740c040-9f5e-4bd8-ae72-d2a6f634ab99"),
                            CookingId = new Guid("8b578d2c-8819-4c50-bf9a-ab33cd6a1ea4"),
                            CreatedAt = new DateTime(2021, 5, 25, 4, 56, 44, 775, DateTimeKind.Utc).AddTicks(3197),
                            Step = "2nd step : Prepare the ingredients",
                            Time = "",
                            TotalStep = 0,
                            UpdatedAt = new DateTime(2021, 5, 25, 4, 56, 44, 775, DateTimeKind.Utc).AddTicks(3199)
                        },
                        new
                        {
                            Id = new Guid("414ee824-29f6-4679-b43b-7f70e9f00f2a"),
                            CookingId = new Guid("8b578d2c-8819-4c50-bf9a-ab33cd6a1ea4"),
                            CreatedAt = new DateTime(2021, 5, 25, 4, 56, 44, 775, DateTimeKind.Utc).AddTicks(3210),
                            Step = "3rd Step : Now the is ingredients is ready we proceed to cook the dish!",
                            Time = "",
                            TotalStep = 0,
                            UpdatedAt = new DateTime(2021, 5, 25, 4, 56, 44, 775, DateTimeKind.Utc).AddTicks(3211)
                        },
                        new
                        {
                            Id = new Guid("9c4c3bb7-1cf5-4cbe-9ebb-d83555f88426"),
                            CookingId = new Guid("8b578d2c-8819-4c50-bf9a-ab33cd6a1ea4"),
                            CreatedAt = new DateTime(2021, 5, 25, 4, 56, 44, 775, DateTimeKind.Utc).AddTicks(3219),
                            Step = "4th Step : Light up the stove and  heat the pan just slight ",
                            Time = "",
                            TotalStep = 0,
                            UpdatedAt = new DateTime(2021, 5, 25, 4, 56, 44, 775, DateTimeKind.Utc).AddTicks(3220)
                        },
                        new
                        {
                            Id = new Guid("95466927-2a0b-4594-8f6a-76d4504e5b84"),
                            CookingId = new Guid("8b578d2c-8819-4c50-bf9a-ab33cd6a1ea4"),
                            CreatedAt = new DateTime(2021, 5, 25, 4, 56, 44, 775, DateTimeKind.Utc).AddTicks(3228),
                            Step = "5th Step : Put the vegetable oil and heat it just slight and put the onions and garlic first.",
                            Time = "",
                            TotalStep = 0,
                            UpdatedAt = new DateTime(2021, 5, 25, 4, 56, 44, 775, DateTimeKind.Utc).AddTicks(3229)
                        },
                        new
                        {
                            Id = new Guid("75a015df-929d-4bda-bc7f-dbd78b3860b5"),
                            CookingId = new Guid("8b578d2c-8819-4c50-bf9a-ab33cd6a1ea4"),
                            CreatedAt = new DateTime(2021, 5, 25, 4, 56, 44, 775, DateTimeKind.Utc).AddTicks(3240),
                            Step = "6th Step : When the onions and garlics are smells good or the color is brown then just put the chicken thighs and cook it for 10mns to 15mns",
                            Time = "",
                            TotalStep = 0,
                            UpdatedAt = new DateTime(2021, 5, 25, 4, 56, 44, 775, DateTimeKind.Utc).AddTicks(3241)
                        },
                        new
                        {
                            Id = new Guid("d8baa664-dafe-45e5-b234-724c80810dec"),
                            CookingId = new Guid("8b578d2c-8819-4c50-bf9a-ab33cd6a1ea4"),
                            CreatedAt = new DateTime(2021, 5, 25, 4, 56, 44, 775, DateTimeKind.Utc).AddTicks(3248),
                            Step = "7th Step : Add the soy sauce and vinegar then add peppercorns, bay leaves and green onion then add a half water of cup",
                            Time = "",
                            TotalStep = 0,
                            UpdatedAt = new DateTime(2021, 5, 25, 4, 56, 44, 775, DateTimeKind.Utc).AddTicks(3249)
                        },
                        new
                        {
                            Id = new Guid("63db5447-986e-4136-b81f-afa50230d24f"),
                            CookingId = new Guid("8b578d2c-8819-4c50-bf9a-ab33cd6a1ea4"),
                            CreatedAt = new DateTime(2021, 5, 25, 4, 56, 44, 775, DateTimeKind.Utc).AddTicks(3258),
                            Step = "8th Step : Wait for 10 to 15mns to cook the adobo and then check your dish if the dish is yummy else just add more soy sauce and salt base on the your taste of food and were done! Thank you for following our cooking recipe.",
                            Time = "",
                            TotalStep = 0,
                            UpdatedAt = new DateTime(2021, 5, 25, 4, 56, 44, 775, DateTimeKind.Utc).AddTicks(3259)
                        });
                });

            modelBuilder.Entity("CookingRecipe.Web.Infrastructures.Domain.Models.User", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Address")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("EmailAddress")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("FirstName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("FullName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("LoginRetries")
                        .HasColumnType("int");

                    b.Property<int>("LoginStatus")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Surname")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("24551e81-1887-4288-89f4-7d4d433120fa"),
                            Address = "Dinalupihan",
                            CreatedAt = new DateTime(2021, 5, 25, 4, 56, 43, 691, DateTimeKind.Utc).AddTicks(8888),
                            EmailAddress = "cdbcasupanan@gmail.com",
                            FirstName = "Cd",
                            FullName = "CD Casupanan",
                            Gender = 0,
                            LastName = "Casupanan",
                            LoginRetries = 0,
                            LoginStatus = 0,
                            Password = "$2b$10$zsNJKcoYMCWUZc156h8pfOcHUAQZ.msqshCQFRtsF9p39dcxn6cqu",
                            PhoneNumber = "123456789",
                            Surname = "cdbcasupanan",
                            UpdatedAt = new DateTime(2021, 5, 25, 4, 56, 43, 691, DateTimeKind.Utc).AddTicks(8924)
                        },
                        new
                        {
                            Id = new Guid("62fb0427-e259-4874-b904-5f5d4d6c4b9e"),
                            Address = "Dinalupihan",
                            CreatedAt = new DateTime(2021, 5, 25, 4, 56, 43, 778, DateTimeKind.Utc).AddTicks(3510),
                            EmailAddress = "Xyrille@gmail.com",
                            FirstName = "Xyrille",
                            FullName = "Xyrille Mamalateo",
                            Gender = 1,
                            LastName = "Mamalateo",
                            LoginRetries = 0,
                            LoginStatus = 0,
                            Password = "$2b$10$zsNJKcoYMCWUZc156h8pfOcHUAQZ.msqshCQFRtsF9p39dcxn6cqu",
                            PhoneNumber = "123456789",
                            Surname = "XyAnn",
                            UpdatedAt = new DateTime(2021, 5, 25, 4, 56, 43, 778, DateTimeKind.Utc).AddTicks(3531)
                        },
                        new
                        {
                            Id = new Guid("385fd1f1-82a6-4eb8-826f-89d8873bcdb1"),
                            Address = "Dinalupihan",
                            CreatedAt = new DateTime(2021, 5, 25, 4, 56, 43, 865, DateTimeKind.Utc).AddTicks(6314),
                            EmailAddress = "Allan@gmail.com",
                            FirstName = "Allan",
                            FullName = "Allan Chavez",
                            Gender = 0,
                            LastName = "Chavez",
                            LoginRetries = 0,
                            LoginStatus = 0,
                            Password = "$2b$10$zsNJKcoYMCWUZc156h8pfOcHUAQZ.msqshCQFRtsF9p39dcxn6cqu",
                            PhoneNumber = "123456789",
                            Surname = "Allan",
                            UpdatedAt = new DateTime(2021, 5, 25, 4, 56, 43, 865, DateTimeKind.Utc).AddTicks(6334)
                        },
                        new
                        {
                            Id = new Guid("a09573f5-62b9-4548-b153-4d2eac8ef29e"),
                            Address = "Dinalupihan",
                            CreatedAt = new DateTime(2021, 5, 25, 4, 56, 43, 954, DateTimeKind.Utc).AddTicks(8352),
                            EmailAddress = "Luisa@gmail.com",
                            FirstName = "Luisa",
                            FullName = "Luisa Kathrina Reyes",
                            Gender = 1,
                            LastName = "Reyes",
                            LoginRetries = 0,
                            LoginStatus = 0,
                            Password = "$2b$10$zsNJKcoYMCWUZc156h8pfOcHUAQZ.msqshCQFRtsF9p39dcxn6cqu",
                            PhoneNumber = "123456789",
                            Surname = "LuisaKath",
                            UpdatedAt = new DateTime(2021, 5, 25, 4, 56, 43, 954, DateTimeKind.Utc).AddTicks(8403)
                        },
                        new
                        {
                            Id = new Guid("984797ad-c1c8-4d36-a527-80e41dd6592e"),
                            Address = "Dinalupihan",
                            CreatedAt = new DateTime(2021, 5, 25, 4, 56, 44, 50, DateTimeKind.Utc).AddTicks(5510),
                            EmailAddress = "larich@gmail.com",
                            FirstName = "Larich",
                            FullName = "Larich Morales",
                            Gender = 1,
                            LastName = "Morales",
                            LoginRetries = 0,
                            LoginStatus = 0,
                            Password = "$2b$10$zsNJKcoYMCWUZc156h8pfOcHUAQZ.msqshCQFRtsF9p39dcxn6cqu",
                            PhoneNumber = "123456789",
                            Surname = "Larich01",
                            UpdatedAt = new DateTime(2021, 5, 25, 4, 56, 44, 50, DateTimeKind.Utc).AddTicks(5562)
                        },
                        new
                        {
                            Id = new Guid("e5037a48-8f1e-4811-8d51-72cef2238ce3"),
                            Address = "Dinalupihan",
                            CreatedAt = new DateTime(2021, 5, 25, 4, 56, 44, 141, DateTimeKind.Utc).AddTicks(4430),
                            EmailAddress = "jane@gmail.com",
                            FirstName = "Jane",
                            FullName = "Jane Ticar",
                            Gender = 1,
                            LastName = "Ticar",
                            LoginRetries = 0,
                            LoginStatus = 0,
                            Password = "$2b$10$zsNJKcoYMCWUZc156h8pfOcHUAQZ.msqshCQFRtsF9p39dcxn6cqu",
                            PhoneNumber = "123456789",
                            Surname = "Jane02",
                            UpdatedAt = new DateTime(2021, 5, 25, 4, 56, 44, 141, DateTimeKind.Utc).AddTicks(4499)
                        },
                        new
                        {
                            Id = new Guid("f178c3cb-db20-436d-a2e2-36d34772dba8"),
                            Address = "Dinalupihan",
                            CreatedAt = new DateTime(2021, 5, 25, 4, 56, 44, 228, DateTimeKind.Utc).AddTicks(343),
                            EmailAddress = "Wesley@gmail.com",
                            FirstName = "Wesley",
                            FullName = "Wesley SA",
                            Gender = 0,
                            LastName = "SA",
                            LoginRetries = 0,
                            LoginStatus = 0,
                            Password = "$2b$10$zsNJKcoYMCWUZc156h8pfOcHUAQZ.msqshCQFRtsF9p39dcxn6cqu",
                            PhoneNumber = "123456789",
                            Surname = "Wesley03",
                            UpdatedAt = new DateTime(2021, 5, 25, 4, 56, 44, 228, DateTimeKind.Utc).AddTicks(391)
                        },
                        new
                        {
                            Id = new Guid("e358f015-6a5f-4a20-8718-513a23fef0fd"),
                            Address = "Dinalupihan",
                            CreatedAt = new DateTime(2021, 5, 25, 4, 56, 44, 314, DateTimeKind.Utc).AddTicks(6989),
                            EmailAddress = "Reniel@gmail.com",
                            FirstName = "Reniel ",
                            FullName = "$2b$10$zsNJKcoYMCWUZc156h8pfOcHUAQZ.msqshCQFRtsF9p39dcxn6cqu",
                            Gender = 0,
                            LastName = "David",
                            LoginRetries = 0,
                            LoginStatus = 0,
                            Password = "123456789",
                            PhoneNumber = "123456789",
                            Surname = "Reniel04",
                            UpdatedAt = new DateTime(2021, 5, 25, 4, 56, 44, 314, DateTimeKind.Utc).AddTicks(7043)
                        },
                        new
                        {
                            Id = new Guid("b36f7f45-1b05-4905-9a66-8183809ff8c8"),
                            Address = "Dinalupihan",
                            CreatedAt = new DateTime(2021, 5, 25, 4, 56, 44, 414, DateTimeKind.Utc).AddTicks(3254),
                            EmailAddress = "Jhon@gmail.com",
                            FirstName = "Jhon Cedric",
                            FullName = "$2b$10$zsNJKcoYMCWUZc156h8pfOcHUAQZ.msqshCQFRtsF9p39dcxn6cqu",
                            Gender = 0,
                            LastName = "Romano",
                            LoginRetries = 0,
                            LoginStatus = 0,
                            Password = "123456789",
                            PhoneNumber = "123456789",
                            Surname = "Jhon06",
                            UpdatedAt = new DateTime(2021, 5, 25, 4, 56, 44, 414, DateTimeKind.Utc).AddTicks(3303)
                        },
                        new
                        {
                            Id = new Guid("41494e0e-cde7-46de-897c-a8369fba5ba9"),
                            Address = "Dinalupihan",
                            CreatedAt = new DateTime(2021, 5, 25, 4, 56, 44, 505, DateTimeKind.Utc).AddTicks(5015),
                            EmailAddress = "Elmo@gmail.com",
                            FirstName = "Elmo",
                            FullName = "Elmo Cahilo",
                            Gender = 0,
                            LastName = "Cahilo",
                            LoginRetries = 0,
                            LoginStatus = 0,
                            Password = "$2b$10$zsNJKcoYMCWUZc156h8pfOcHUAQZ.msqshCQFRtsF9p39dcxn6cqu",
                            PhoneNumber = "123456789",
                            Surname = "Elmo07",
                            UpdatedAt = new DateTime(2021, 5, 25, 4, 56, 44, 505, DateTimeKind.Utc).AddTicks(5065)
                        },
                        new
                        {
                            Id = new Guid("83349c71-bbe2-4c2d-a9a5-3d555a00305c"),
                            Address = "Dinalupihan",
                            CreatedAt = new DateTime(2021, 5, 25, 4, 56, 44, 592, DateTimeKind.Utc).AddTicks(9633),
                            EmailAddress = "Jake@gmail.com",
                            FirstName = "Jake Renzo",
                            FullName = "Jake Renzo Carlos",
                            Gender = 0,
                            LastName = "Carlos",
                            LoginRetries = 0,
                            LoginStatus = 0,
                            Password = "$2b$10$zsNJKcoYMCWUZc156h8pfOcHUAQZ.msqshCQFRtsF9p39dcxn6cqu",
                            PhoneNumber = "123456789",
                            Surname = "Jake08",
                            UpdatedAt = new DateTime(2021, 5, 25, 4, 56, 44, 592, DateTimeKind.Utc).AddTicks(9713)
                        },
                        new
                        {
                            Id = new Guid("634e0321-5f02-458b-a2b8-7bd07bc86672"),
                            Address = "Dinalupihan",
                            CreatedAt = new DateTime(2021, 5, 25, 4, 56, 44, 681, DateTimeKind.Utc).AddTicks(5799),
                            EmailAddress = "Christian@gmail.com",
                            FirstName = "Christian",
                            FullName = "Christian Cruz",
                            Gender = 0,
                            LastName = "Cruz",
                            LoginRetries = 0,
                            LoginStatus = 0,
                            Password = "$2b$10$zsNJKcoYMCWUZc156h8pfOcHUAQZ.msqshCQFRtsF9p39dcxn6cqu",
                            PhoneNumber = "123456789",
                            Surname = "Christian09",
                            UpdatedAt = new DateTime(2021, 5, 25, 4, 56, 44, 681, DateTimeKind.Utc).AddTicks(5817)
                        },
                        new
                        {
                            Id = new Guid("9c304fab-d362-483c-be13-885381731ba8"),
                            Address = "Dinalupihan",
                            CreatedAt = new DateTime(2021, 5, 25, 4, 56, 44, 771, DateTimeKind.Utc).AddTicks(9970),
                            EmailAddress = "mama@gmail.com",
                            FirstName = "MAMA",
                            FullName = "MAMA KO",
                            Gender = 1,
                            LastName = "KO",
                            LoginRetries = 0,
                            LoginStatus = 0,
                            Password = "$2b$10$zsNJKcoYMCWUZc156h8pfOcHUAQZ.msqshCQFRtsF9p39dcxn6cqu",
                            PhoneNumber = "123456789",
                            Surname = "MAMA00",
                            UpdatedAt = new DateTime(2021, 5, 25, 4, 56, 44, 771, DateTimeKind.Utc).AddTicks(9990)
                        });
                });

            modelBuilder.Entity("CookingRecipe.Web.Infrastructures.Domain.Models.UserRole", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("880e8918-8e8f-488b-9ffc-bd06285881dc"),
                            CreatedAt = new DateTime(2021, 5, 25, 4, 56, 44, 774, DateTimeKind.Utc).AddTicks(4587),
                            Role = 1,
                            UpdatedAt = new DateTime(2021, 5, 25, 4, 56, 44, 774, DateTimeKind.Utc).AddTicks(4590),
                            UserId = new Guid("24551e81-1887-4288-89f4-7d4d433120fa")
                        },
                        new
                        {
                            Id = new Guid("f5cd2ec2-8f70-4c06-917b-188a245e61ff"),
                            CreatedAt = new DateTime(2021, 5, 25, 4, 56, 44, 774, DateTimeKind.Utc).AddTicks(5153),
                            Role = 1,
                            UpdatedAt = new DateTime(2021, 5, 25, 4, 56, 44, 774, DateTimeKind.Utc).AddTicks(5155),
                            UserId = new Guid("62fb0427-e259-4874-b904-5f5d4d6c4b9e")
                        },
                        new
                        {
                            Id = new Guid("8436f69d-200e-4ef9-81bd-46038f11d644"),
                            CreatedAt = new DateTime(2021, 5, 25, 4, 56, 44, 774, DateTimeKind.Utc).AddTicks(5197),
                            Role = 1,
                            UpdatedAt = new DateTime(2021, 5, 25, 4, 56, 44, 774, DateTimeKind.Utc).AddTicks(5198),
                            UserId = new Guid("1e5a951c-ae94-42dd-b01b-62460c556408")
                        },
                        new
                        {
                            Id = new Guid("87abcfc2-60f1-4632-9e06-bc363d57b88b"),
                            CreatedAt = new DateTime(2021, 5, 25, 4, 56, 44, 774, DateTimeKind.Utc).AddTicks(5209),
                            Role = 1,
                            UpdatedAt = new DateTime(2021, 5, 25, 4, 56, 44, 774, DateTimeKind.Utc).AddTicks(5210),
                            UserId = new Guid("7f5c0d24-0d38-48b4-a5b7-bd6b5e3bbe22")
                        },
                        new
                        {
                            Id = new Guid("9cc6bada-f43f-47e2-b8e6-462f97f0a9ed"),
                            CreatedAt = new DateTime(2021, 5, 25, 4, 56, 44, 774, DateTimeKind.Utc).AddTicks(5219),
                            Role = 1,
                            UpdatedAt = new DateTime(2021, 5, 25, 4, 56, 44, 774, DateTimeKind.Utc).AddTicks(5220),
                            UserId = new Guid("385fd1f1-82a6-4eb8-826f-89d8873bcdb1")
                        },
                        new
                        {
                            Id = new Guid("bd436a4b-dac7-43c7-bd5d-1a434da9a99c"),
                            CreatedAt = new DateTime(2021, 5, 25, 4, 56, 44, 774, DateTimeKind.Utc).AddTicks(5232),
                            Role = 1,
                            UpdatedAt = new DateTime(2021, 5, 25, 4, 56, 44, 774, DateTimeKind.Utc).AddTicks(5233),
                            UserId = new Guid("a09573f5-62b9-4548-b153-4d2eac8ef29e")
                        },
                        new
                        {
                            Id = new Guid("ec54e10c-21eb-4509-8d13-23edcc6b494d"),
                            CreatedAt = new DateTime(2021, 5, 25, 4, 56, 44, 774, DateTimeKind.Utc).AddTicks(5242),
                            Role = 1,
                            UpdatedAt = new DateTime(2021, 5, 25, 4, 56, 44, 774, DateTimeKind.Utc).AddTicks(5243),
                            UserId = new Guid("984797ad-c1c8-4d36-a527-80e41dd6592e")
                        },
                        new
                        {
                            Id = new Guid("82400738-a126-4341-a8bc-dd38409174d8"),
                            CreatedAt = new DateTime(2021, 5, 25, 4, 56, 44, 774, DateTimeKind.Utc).AddTicks(5252),
                            Role = 1,
                            UpdatedAt = new DateTime(2021, 5, 25, 4, 56, 44, 774, DateTimeKind.Utc).AddTicks(5254),
                            UserId = new Guid("e5037a48-8f1e-4811-8d51-72cef2238ce3")
                        },
                        new
                        {
                            Id = new Guid("b95ac303-abac-43cd-801d-02bd480c231b"),
                            CreatedAt = new DateTime(2021, 5, 25, 4, 56, 44, 774, DateTimeKind.Utc).AddTicks(5263),
                            Role = 1,
                            UpdatedAt = new DateTime(2021, 5, 25, 4, 56, 44, 774, DateTimeKind.Utc).AddTicks(5265),
                            UserId = new Guid("f178c3cb-db20-436d-a2e2-36d34772dba8")
                        },
                        new
                        {
                            Id = new Guid("f72a76a3-bd79-4c36-a454-2dfc8077cdc1"),
                            CreatedAt = new DateTime(2021, 5, 25, 4, 56, 44, 774, DateTimeKind.Utc).AddTicks(5275),
                            Role = 1,
                            UpdatedAt = new DateTime(2021, 5, 25, 4, 56, 44, 774, DateTimeKind.Utc).AddTicks(5277),
                            UserId = new Guid("e358f015-6a5f-4a20-8718-513a23fef0fd")
                        },
                        new
                        {
                            Id = new Guid("5acf73f4-d64e-4a58-9762-f42067d43fa6"),
                            CreatedAt = new DateTime(2021, 5, 25, 4, 56, 44, 774, DateTimeKind.Utc).AddTicks(5284),
                            Role = 1,
                            UpdatedAt = new DateTime(2021, 5, 25, 4, 56, 44, 774, DateTimeKind.Utc).AddTicks(5286),
                            UserId = new Guid("b36f7f45-1b05-4905-9a66-8183809ff8c8")
                        },
                        new
                        {
                            Id = new Guid("5d56eb33-d5d2-4bdc-9a06-7e07f1b32f30"),
                            CreatedAt = new DateTime(2021, 5, 25, 4, 56, 44, 774, DateTimeKind.Utc).AddTicks(5295),
                            Role = 1,
                            UpdatedAt = new DateTime(2021, 5, 25, 4, 56, 44, 774, DateTimeKind.Utc).AddTicks(5296),
                            UserId = new Guid("83349c71-bbe2-4c2d-a9a5-3d555a00305c")
                        },
                        new
                        {
                            Id = new Guid("dc49b9f8-254d-4bca-82db-a4aff22287c8"),
                            CreatedAt = new DateTime(2021, 5, 25, 4, 56, 44, 774, DateTimeKind.Utc).AddTicks(5305),
                            Role = 1,
                            UpdatedAt = new DateTime(2021, 5, 25, 4, 56, 44, 774, DateTimeKind.Utc).AddTicks(5306),
                            UserId = new Guid("634e0321-5f02-458b-a2b8-7bd07bc86672")
                        },
                        new
                        {
                            Id = new Guid("faf2ed2d-370e-48cc-aa57-cdee56d72fdb"),
                            CreatedAt = new DateTime(2021, 5, 25, 4, 56, 44, 774, DateTimeKind.Utc).AddTicks(5313),
                            Role = 1,
                            UpdatedAt = new DateTime(2021, 5, 25, 4, 56, 44, 774, DateTimeKind.Utc).AddTicks(5314),
                            UserId = new Guid("9c304fab-d362-483c-be13-885381731ba8")
                        });
                });

            modelBuilder.Entity("CookingRecipe.Web.Infrastructures.Domain.Models.Ingredient", b =>
                {
                    b.HasOne("CookingRecipe.Web.Infrastructures.Domain.Models.Cooking", "Cooking")
                        .WithMany("Ingredients")
                        .HasForeignKey("CookingId");
                });

            modelBuilder.Entity("CookingRecipe.Web.Infrastructures.Domain.Models.Instruction", b =>
                {
                    b.HasOne("CookingRecipe.Web.Infrastructures.Domain.Models.Cooking", "Cooking")
                        .WithMany("Instructions")
                        .HasForeignKey("CookingId");
                });
#pragma warning restore 612, 618
        }
    }
}
